In [1]:
path=r"C:\Users\Hp\Documents\NareshIT\Machine Learning\Linear Regression\California_updated.csv"

In [3]:
import sklearn 
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns 

In [5]:
df=pd.read_csv(path)

In [7]:
df.head()

MedInc  HouseAge  Population  AveOccup  AveRooms  Latitude  MedHouseVal
0  2.344766  0.982143   -0.974429 -0.049597  0.628559  1.052548        4.526
1  2.332238 -0.607019    0.861439 -0.092512  0.327041  1.043185        3.585
2  1.782699  1.856182   -0.820777 -0.025843  1.155620  1.038503        3.521
3  0.932968  1.856182   -0.766028 -0.050329  0.156966  1.038503        3.413
4 -0.012881  1.856182   -0.759847 -0.085616  0.344711  1.038503        3.422

In [9]:
X=df.drop('MedHouseVal',axis=1)
y=df['MedHouseVal']

In [11]:
X.head()

MedInc  HouseAge  Population  AveOccup  AveRooms  Latitude
0  2.344766  0.982143   -0.974429 -0.049597  0.628559  1.052548
1  2.332238 -0.607019    0.861439 -0.092512  0.327041  1.043185
2  1.782699  1.856182   -0.820777 -0.025843  1.155620  1.038503
3  0.932968  1.856182   -0.766028 -0.050329  0.156966  1.038503
4 -0.012881  1.856182   -0.759847 -0.085616  0.344711  1.038503

In [13]:
y

0        4.526
1        3.585
2        3.521
3        3.413
4        3.422
         ...  
20635    0.781
20636    0.771
20637    0.923
20638    0.847
20639    0.894
Name: MedHouseVal, Length: 20640, dtype: float64

In [15]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1234)

In [17]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(X_train,y_train)

LinearRegression()

In [19]:
y_pred=lr.predict(X_test)

In [21]:
y_pred

array([2.30473678, 3.26212585, 2.25235989, ..., 1.39434401, 2.39395217,
       1.71946446])

In [23]:
from sklearn.metrics import mean_squared_error, root_mean_squared_error, r2_score

In [33]:
MSE=mean_squared_error(y_test,y_pred)
RMSE=root_mean_squared_error(y_test,y_pred)
R2=r2_score(y_test,y_pred)

In [35]:
print('MSE :',MSE)
print('RMSE :',RMSE)                                             
print('R2 :',R2)

MSE : 0.6676008481118303
RMSE : 0.8170684476295914
R2 : 0.5065090715994582


In [37]:
import numpy as np
np.mean(y)

2.068558169089147

## Model Saving
- we can save model in two ways :
    - using pickle: .pkl
    - using joblib: .joblib

**pickle**

In [42]:
import pickle

- dump
    - we will save the model in .pkl format
  
    - it expects the model and location
 
  
    - it is similar to file open in write format
 

    - here also we will open the file with write bytes format

- load

  
    - similar way it needs only file name in read bytes format 

In [46]:
# our model name is : lr
# where i want to save : same directory 
# on what name i want to save : california 
# on what extension i want to save : .pkl
# file name : california.pkl
# write format is : wb

In [48]:
str1='hello'
with open('dummy.txt','w') as file:
    file.write(str1)

In [52]:
with open('california.pkl','wb') as file:
    pickle.dump(lr,file)

In [54]:
with open('california.pkl','rb') as file:
    loaded_file=pickle.load(file)

In [56]:
loaded_file

LinearRegression()

**real time prediction**
- how many values we need to pass
- the model developed by using 6 columns
- when we pass single list 1D, model will throw error
- model expects 2D data
- because 2D gives flexibility to process multiple question at a time 

In [62]:
loaded_file.predict([10,20,30,40,50,60])  # Note the error

C:\Users\Hp\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


ValueError: Expected 2D array, got 1D array instead:
array=[10 20 30 40 50 60].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [67]:
q1=[20,40,60,20,10,90]
q2=[23,40,55,68,54,12]
q=[q1,q2]
loaded_file.predict(q)

C:\Users\Hp\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([19.04188292, 23.36980537])

In [69]:
q1=[20,40,60,20,10,90]
q2=[23,40,55,68,54,12]
q3=[10,20,30,40,50,60]
q=[q1,q2,q3]
loaded_file.predict(q)

C:\Users\Hp\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([19.04188292, 23.36980537,  4.805776  ])

In [75]:
X_test.values

array([[-0.09973335,  1.85618152, -0.71657708, -0.1295939 , -0.23470435,
         1.01041149],
       [ 0.88522503,  1.85618152,  0.36781217, -0.00959844,  0.2829428 ,
        -0.69846949],
       [ 0.00227869,  1.22051689, -0.7633789 , -0.12996558, -0.27878108,
         1.00572963],
       ...,
       [-0.69954101,  0.10810379, -1.04507285, -0.04511012, -0.13862674,
         1.11341254],
       [ 0.00227869,  1.85618152, -0.9179132 , -0.1134721 , -0.42105787,
         1.04786642],
       [-0.06088666, -1.08376738, -0.36600499,  0.0038624 , -0.02664503,
         0.55158865]])

In [77]:
loaded_file.predict(X_test.values)

C:\Users\Hp\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([2.30473678, 3.26212585, 2.25235989, ..., 1.39434401, 2.39395217,
       1.71946446])

In [81]:
loaded_file.predict(X_test.values[0])

C:\Users\Hp\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


ValueError: Expected 2D array, got 1D array instead:
array=[-0.09973335  1.85618152 -0.71657708 -0.1295939  -0.23470435  1.01041149].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [83]:
# generally the model we save, client ppl will use that but they don't know on how many columns model is train 

In [85]:
dict1={'model':lr,
       'columns':X_train.columns,
       'no. of columns':len(X_train.columns)
}

In [87]:
with open('california1.pkl','wb') as file:
    pickle.dump(dict1,file)

In [91]:
with open('california1.pkl','rb') as file:
    loaded_model=pickle.load(file)

In [93]:
loaded_model

{'model': LinearRegression(),
 'columns': Index(['MedInc', 'HouseAge', 'Population', 'AveOccup', 'AveRooms', 'Latitude'], dtype='object'),
 'no. of columns': 6}

In [95]:
Model=loaded_model['model']
Model.predict([[10,20,30,40,50,60]])

C:\Users\Hp\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([4.805776])

## joblib
- dump
- load 

In [100]:
import joblib 

In [102]:
file='california.joblib'
joblib.dump(lr,file)

['california.joblib']

In [104]:
loaded_model1=joblib.load(file)

In [106]:
loaded_model1

LinearRegression()

In [108]:
loaded_model1.predict([[10,20,30,40,50,60]])

C:\Users\Hp\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([4.805776])

In [110]:
dict1={'model':lr,
       'columns':X_train.columns,
       'no. of columns':len(X_train.columns)
}

In [112]:
file='california.joblib'
joblib.dump(dict1,file)

['california.joblib']

In [114]:
loaded_model2=joblib.load(file)

In [116]:
loaded_model2

{'model': LinearRegression(),
 'columns': Index(['MedInc', 'HouseAge', 'Population', 'AveOccup', 'AveRooms', 'Latitude'], dtype='object'),
 'no. of columns': 6}

In [122]:
loaded_model2['model'].predict([[10,20,30,40,50,60]])

C:\Users\Hp\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([4.805776])

- **joblib is mainly used for sklearn models**
- **fast and best compared to .pkl**

In [125]:
loaded_model2['model'].predict([10,20,30,40,50,60]).reshape(-1,1)

C:\Users\Hp\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


ValueError: Expected 2D array, got 1D array instead:
array=[10 20 30 40 50 60].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.